### ISSUE TITLE
code bug

### ISSUE THREAD

**Issue by MeycL** [Adamli12/CUT_24#2]
Traceback (most recent call last):
  File "run_cut.py", line 16, in <module>
    run_recbole_cdr(model=args.model, config_file_list=config_file_list)
  File "\CUT_24-main\CUT\quick_start\quick_start.py", line 29, in run_recbole_cdr
    config = CDRConfig(model=model, config_file_list=config_file_list, config_dict=config_dict)
  File "\CUT_24-main\CUT\config\configurator.py", line 72, in __init__
    self._set_train_neg_sample_args()
  File "\env\lib\site-packages\recbole\config\configurator.py", line 351, in _set_train_neg_sample_args
    neg_sampling = self.final_config_dict['neg_sampling']
KeyError: 'neg_sampling'

My recbole version is 1.0.1. Could you please tell me why this problem is occurring?

**Comment by Adamli12** [comment]
it seems like recbole updated the configurator.py in version 1.1.1, I have tried 1.1.1 version and it works well.
Thank you for your reminder, and I have updated the requirements.
